// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nseoxvcyikyvqvcitlsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zZW94dmN5aWt5dnF2Y2l0bHNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyOTU4NjAsImV4cCI6MjA2Mjg3MTg2MH0.hFchOWwumMuxDeTQ-y1yQCltKzFBRfJGb3MbBOUq8_0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);